import { useEffect, useRef, useState} from 'react';
import Head from 'next/head';
import Image from 'next/image';
import { useIntersection } from 'react-use';
import useEmblaCarousel from 'embla-carousel-react';
import { WheelGesturesPlugin } from 'embla-carousel-wheel-gestures';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import emstyles from './index.module.css';
import throttle from 'just-throttle';
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [target, setTarget] = useState<Element | undefined>(undefined);
  const containerRef = useRef<HTMLDivElement>(null);
  const lastItemRef = useRef<HTMLDivElement>(null);
  const firstItemRef = useRef<HTMLDivElement>(null);

  const [emblaRef, emblaApi] = useEmblaCarousel({ 
    loop: false,
    align: 'start',
    dragFree: true, 
    speed: 11,
    skipSnaps: true,
    inViewThreshold: 0.8
  }, [WheelGesturesPlugin({
    forceWheelAxis: 'y',
    target: target
  })]);

  const intersectionRef = useRef(null);
  const intersection = useIntersection(intersectionRef, {
    root: null,
    rootMargin: '0px',
    threshold: 1
  });
  const intersectionLast = useIntersection(lastItemRef, {
    root: null,
    rootMargin: '0px',
    threshold: .8
  });
  const intersectionFirst = useIntersection(firstItemRef, {
    root: null,
    rootMargin: '0px',
    threshold: .8
  });


  useEffect(() => {
    const trackWheel = throttle((event: WheelEvent) => {
      if (emblaApi) {
        if( 
            containerRef.current && intersection?.isIntersecting &&
            ((event.deltaY < 0 && !intersectionFirst?.isIntersecting) || // scroll up --> scrollProgress >= 0.05
             (event.deltaY > 0 && !intersectionLast?.isIntersecting)) // scroll down, <-- scrollProgress <= 0.8
        ){
          setTarget(containerRef.current);
        } else {
          setTarget(undefined);
        }
      }
    }, 50, { leading: true });
    window.addEventListener('wheel', trackWheel);
    return () => {
      window.removeEventListener('wheel', trackWheel);
    }
  }, [emblaApi, containerRef, intersection, intersectionLast, intersectionFirst])


  return (
    <div ref={containerRef}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
      <div className={`${emstyles.embla} max-w-5xl mx-auto`} ref={intersectionRef}>
        <div className={emstyles.embla__viewport} ref={emblaRef}>
          <div className={emstyles.embla__container}>
            <div ref={firstItemRef} className={`${emstyles.embla__slide} rounded bg-gradient-to-r from-cyan-500 to-blue-500`}>Slide 1</div>
            <div className={`${emstyles.embla__slide} rounded bg-[radial-gradient(ellipse_at_bottom_left,_var(--tw-gradient-stops))] from-purple-200 via-purple-400 to-purple-800`}>Slide 2</div>
            <div className={`${emstyles.embla__slide} rounded bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500`}>Slide 3</div>
            <div className={`${emstyles.embla__slide} rounded bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-yellow-100 via-yellow-300 to-yellow-500`}>Slide 4</div>
            <div className={`${emstyles.embla__slide} rounded bg-[radial-gradient(ellipse_at_bottom,_var(--tw-gradient-stops))] from-green-500 to-green-700`}>Slide 5</div>
            <div ref={lastItemRef} className={`${emstyles.embla__slide} rounded bg-gradient-to-r from-red-200 to-red-600`}>Slide 6</div>
          </div>
        </div>
      </div>
      <div className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </div>
    </div>
  )
}
